name: Code Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    uses: robert7/workflows/.github/workflows/node-ci.yml@v0.4.0
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
